### ISSUE TITLE
not minify after use hexo generate

### ISSUE THREAD

**Issue by masterviana** [hexojs/hexo-clean-css#1]
I install this plugin, and i expect to see all my css files with file.min.css, but after execute hexo generate i dont see nothing here my configuration clean_css:
  exclude:

**Comment by curbengh** [comment]
This plugin doesn't rename file.css to file.min.css and ignore existing css files with *.min.css.

**Comment by curbengh** [comment]
Another approach is to rename your css files to "*.min.css" beforehand and disable `exclude:`

``` yml
clean_css:
  exclude: ''
```
